apiVersion: v1
kind: Secret
metadata:
  name: datasource-grafana
  namespace: default
type: Opaque
stringData:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-grafana-loki-query-frontend.default:3100
        access: proxy
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://logs-kube-prometheus-stack-prometheus.default:9090/
        access: proxy